### PR TITLE
Fix linting and spelling errors in source code

### PR DESCRIPTION
**Pull request by dvdgomez**
## Description

Fixed flagged linting errors caught by the `tox -e lint` command. Lint test should now be passing.

## How was the code tested?

Both "tox -e fmt" and "tox -e lint" run on Ubuntu 22.04 LTS.

## Related issues and/or tasks

See related Projects

## Checklist

- [x] I am the author of these changes, or I have the rights to submit them.
- [x] I have added the relevant changes to the README and/or documentation.
- [x] I have self reviewed my own code.
- [x] All requested changes and/or review comments have been resolved.

### CODE REVIEW

**Comment by NucciTheBoss** [comment]
Test failed the first time so I am rerunning again to see if the same behavior is reproduced. The test is timing out because it is taking so long for the slurmd charm to reach active status.

**Comment by dvdgomez** [comment]
> Test failed the first time so I am rerunning again to see if the same behavior is reproduced. The test is timing out because it is taking so long for the slurmd charm to reach active status.

I'm not sure why but there is definitely a race condition with the slurmd charm where it can potentially get stuck. I will open a Jira issue to figure out and fix the race condition in slurmd.

**Comment by NucciTheBoss** [comment]
> I'm not sure why but there is definitely a race condition with the slurmd charm where it can potentially get stuck. I will open a Jira issue to figure out and fix the race condition in slurmd.

Sounds good. I will merge this pull request because the integration tests are doing what they are supposed to do; identifying code smells. This race condition will need to be at the top of the pile for things that we refactor first.

**Review by NucciTheBoss — APPROVED** [review]
LGTM. We'll look into the race condition after we get the charm publishing pipelines built.

**Pull request merged**
